mode: deployment

image:
  repository: "otel/opentelemetry-collector-k8s"

resources:
  limits:
    cpu: 100m
    memory: 200M

useOTLPToExportInternalTelemetry:
  enabled: true
  endpoint: "http://localhost:4318"
  headers:
    - name: "x-opentelemetry-customer"
      value: "a value"
